name = "hammal"
type = "webpack"
account_id = "e90d65257ae4d914cd15c682220dca20"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "you kv id" }
]
